/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib\reverse-theme.source.ts
 * Command: astryx theme build lib\reverse-theme.source.ts
 * CLI: @astryxdesign/cli@0.4.1
 * Core: @astryxdesign/core@0.4.1
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
